### ISSUE TITLE
Website option not visible on GitHub

### ISSUE THREAD

**Issue by ghost** [RabiaZaheer/TSD22SI02#2]
The web site menu option is not visible to me.

**Comment by RabiaZaheer** [comment]
I cant see this option too.

**Comment by ghost** [comment]
> I cant see this option too.

Do you need to turn it on in the settings ?

**Comment by RabiaZaheer** [comment]
I have check all the options in github sittings. I cant find it. 
Give me some time for RND. I will get back soon

**Comment by ghost** [comment]
Looks like select 'Settings' and then Pages in the left side menu and setup the source ?

Regards,
Darryl


________________________________

**Comment by RabiaZaheer** [comment]
I have done that.

**Comment by ghost** [comment]
Session 6 - Class Exercises

Ex02 - How to create an official website in GitHub?
In the repository, create a branch called gh-pages (i.e. github pages).  This is a special branch name where the web pages are stored.

I created the branch, added some html code and sync back to GitHub, but I still cant see a link anywhere.


This is where I think it should be.  https://rabiazaheer.github.io/TSD22Sl02/index.html

is that Sl02 (ess-ell-zero-two) or S102 (ess-one-zero-two) ?

Regards,
Darryl


________________________________
